trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
  displayName: 'Download saker.build'
- script: |
    set -e
    curl -s https://gist.githubusercontent.com/Sipkab/1505a8659af20003ae09295e99d3cba3/raw/azure_ubuntu_jdksetup_variables.sh -o /tmp/azure_ubuntu_jdksetup_variables.sh
    bash /tmp/azure_ubuntu_jdksetup_variables.sh 8 9
  displayName: 'Setup JDKs'
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=$(JAVA_HOME_8_X64);$(JAVA_HOME_9_X64)" -trace pwd://build/build_test.trace test
  displayName: 'Test'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish test trace'
  inputs:
    pathtoPublish: build/build_test.trace
    artifactName: test_trace
- script: java -jar saker.build.jar -bd build "-EUsaker.java.jre.install.locations=$(JAVA_HOME_8_X64);$(JAVA_HOME_9_X64)" -trace pwd://build/build_exportall.trace exportall
  displayName: 'Export'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish export trace'
  inputs:
    pathtoPublish: build/build_exportall.trace
    artifactName: export_trace