name: Saker Build Test
on: workflow_dispatch
jobs:
  build:
    name: Testing Saker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: set up JDK 9
      uses: actions/setup-java@v2
      with:
        java-version: '9'
        distribution: 'adopt'
   
    - name: Building App
      continue-on-error: true
      run: |
         curl -L https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
         java -jar saker.build.jar -bd build compile saker.build

- name: Upload build 
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: build
          path: build
